---
# From the charts list, finding out the OpenEBS chart name.
- name: Getting OpenEBS chart name
  shell: helm ls --all | grep openebs | grep DEPLOYED | awk '{print $1}'
  args:
    executable: /bin/bash
  register: charts

- name: Uninstall OpenEBS
  shell: helm del --purge "{{charts.stdout}}"
  args:
    executable: /bin/bash
  register: purge_out
  until: "'deleted' in purge_out.stdout"
  delay: 20
  retries: 10
  when: "{{soft_uninstall}}" == "no"

- name: Uninstall OpenEBS
  shell: helm del "{{charts.stdout}}"
  args:
    executable: /bin/bash
  register: purge_out
  until: "'deleted' in purge_out.stdout"
  delay: 20
  retries: 10
  when: "{{soft_uninstall}}" == "yes"


- name: Check if OpenEBS namespace is deleted.
  shell: kubectl get ns 
  args:
    executable: /bin/bash
  register: ns_out
  until: "'openebs' not in ns_out.stdout"
  delay: 20
  retries: 10 
 
  

