---
- hosts: localhost
  connection: local

  vars_files:
    - test_vars.yml

  tasks:
    - block:

      ## Generating the testname for deployment
        - include_tasks: /common/utils/create_testname.yml

         ## RECORD START-OF-TEST IN LITMUS RESULT CR
        - include_tasks: /common/utils/update_litmus_result_resource.yml
          vars:
            status: 'SOT'

         ##Actual test
         ## Creating namespaces and making the application for deployment
        - include_tasks: /common/utils/pre_create_app_deploy.yml

        ## Deploying the application
        - include_tasks: /common/utils/deploy_single_app.yml
          vars:
            check_app_pod: 'yes'
            delay: 10
            retries: 100

        ## Fetching the pod name
        - include_tasks: /common/utils/fetch_app_pod.yml

        ## Checking the db is ready for connection
        - include_tasks: /common/utils/check_db_connection.yml

        - set_fact:
            flag: "Pass"

      rescue:
        - set_fact:
            flag: "Fail"

      always:
            ## RECORD END-OF-TEST IN LITMUS RESULT CR
        - include_tasks: /common/utils/update_litmus_result_resource.yml
          vars:
            status: 'EOT'
