#Delete-aws-cluster.yml
#Description: This will delete aws cluster, bucket, tags from subnets and cluster name file

########################################################################################################################################################################

#Steps:
#1. Deleting AWS cluster
#2. Deleting AWS bucket
#3. Deleting cluster name from file
########################################################################################################################################################################

---

- hosts: localhost
  
  vars_files:
    - vars.yml

  vars:
    cluster_name: "{{ lookup('lines', 'grep cluster_name /tmp/aws/cluster_name.csv | cut -d: -f2') }}"

  tasks:
    - block:
        - name: Deleting aws cluster
          command: kops delete cluster --name k8s-{{ cluster_name }}.k8s.local --state=s3://k8s-bucket-{{ cluster_name }} --yes
          ignore_errors: True

        - s3_bucket:
            name: "k8s-bucket-{{ cluster_name }}"
            region: "{{ region }}"
            state: absent
            force: yes

        - name: Deleting cluster name from csv file
          lineinfile:
            state: absent
            path: "/tmp/aws/cluster_name.csv"
            regexp: ""
            mode: 0755

        - name: Set Test Status
          set_fact:
            flag: "Test Passed"
    
      rescue:
        - name: Set Test Status
          set_fact:
            flag: "Test Failed"