# Create an OSEv3 group that contains the masters, nodes, and etcd groups
[OSEv3:children]
masters
nodes
etcd

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password

ansible_ssh_user=root
osm_etcd_image=registry.access.redhat.com/rhel7/etcd:3.2.22

openshift_set_node_ip=true


openshift_deployment_type=openshift-enterprise

openshift_disable_check=disk_availability,memory_availability,docker_storage,docker_image_availability

# uncomment the following to enable htpasswd authentication; defaults to DenyAllPasswordIdentityProvider
#openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]

osm_cluster_network_cidr=172.20.0.0/16
openshift_portal_net=172.21.0.0/16


# host group for masters
[masters]
master_dns

# host group for etcd
[etcd]
master_dns

# host group for nodes, includes region info
[nodes]
master_dns openshift_ip=master_ip openshift_node_group_name='node-config-master-infra'
node1_dns openshift_ip=node1_ip openshift_node_group_name='node-config-compute'
node2_dns openshift_ip=node2_ip openshift_node_group_name='node-config-compute'
node3_dns openshift_ip=node3_ip openshift_node_group_name='node-config-compute'
