apiVersion: batch/v1
kind: Job
metadata:
  name: redis-lg
spec:
  template:
    metadata:
      name: redis-loadgen      
      labels:
        loadgen_lkey: loadgen_lvalue
    spec:
      restartPolicy: Never
      containers:
      - name: redis-lg
        image: vvibhr995/ycsb:test
        command:  ["/bin/bash"]
        args: ["-c","bash ycsb-redis.sh"]
        tty: true
              
