---
##################################################### PREPARATION OF K8S-LOCALHOST BOX #########################################################

pip_local_packages:
  - 'docker-py==1.9.0'

###################################################### PREPARATION OF KUBERNETES ROLE  ##########################################################

# Links for rpm packages that will be installed on all K8s boxes (masters, minions), i.e, 
# these packages will be copied into kubernetes role's .files

k8s_cni_rpm_package: https://packages.cloud.google.com/yum/pool/e7a4403227dd24036f3b0615663a371c4e07a95be5fee53505e647fd8ae58aa6-kubernetes-cni-0.5.1-0.x86_64.rpm

k8s_rpm_package_alias:
  - kubeadm.rpm
  - kubectl.rpm
  - kubelet.rpm

k8s_log_aggregator_url: https://github.com/wercker/stern/releases/download/1.6.0/stern_linux_amd64 

k8s_log_aggregator: stern

# Container images that needs to be placed on all K8s boxes (masters, minions)
# These images will be downloaded, tar'ed and pushed into the kubernetes role's .files

k8s_images:
  - gcr.io/google_containers/pause-amd64:3.0
  - gcr.io/google_containers/etcd-amd64:3.0.17
  - gcr.io/google_containers/kube-scheduler-amd64:v{{ k8s_version }}
  - gcr.io/google_containers/kube-apiserver-amd64:v{{ k8s_version }}
  - gcr.io/google_containers/kube-controller-manager-amd64:v{{ k8s_version }}
  - gcr.io/google_containers/kube-proxy-amd64:v{{ k8s_version }}
  - gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.1
  - gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.1
  - gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.1

###################################################### PREPARATION OF K8S-MASTER ROLE ###########################################################

# Links for scripts to be placed into K8s-master role's .files 

k8s_master_scripts: 
  - https://raw.githubusercontent.com/openebs/openebs/master/k8s/lib/scripts/configure_k8s_master.sh
  - https://raw.githubusercontent.com/openebs/openebs/master/k8s/lib/scripts/configure_k8s_cni.sh

# Container images that needs to be placed in K8s-master box
# These images will be downloaded, tar'ed and pushed into K8s-master role's .files 

weave_images: 
  - weaveworks/weave-kube:{{ weave_version }}
  - weaveworks/weave-npc:{{ weave_version }}

# Link to download default weave template (.yaml) to be placed in roles/kubernetes/templates

weave_template_link: https://raw.githubusercontent.com/openebs/openebs/master/k8s/lib/vagrant/boxes/k8s-weave/external/weave-daemonset-k8s-1.6.yaml

###################################################### PREPARATION OF K8S-HOST ROLE #############################################################

# Links for scripts to be placed into K8s-host role's .files

k8s_host_scripts: 
  - https://raw.githubusercontent.com/openebs/openebs/master/k8s/lib/scripts/configure_k8s_host.sh


