component_depth: 2
languages:
- go
- typescript
exclude:
- /build/plugins/.*
- /build/utils/.*
- /litmus-portal/graphql-server/graph/generated/.*
- /litmus-portal/graphql-server/graph/model/.*
test:
    include:
      - /litmus-portal/frontend/src/**/__tests__/**/*\.{js,jsx,ts,tsx}
      - /litmus-portal/frontend/src/**/?(*\.)(spec|test).{js,jsx,ts,tsx}
