component_depth: 2
languages:
  - go
  - typescript
exclude:
  - /build/plugins/.*
  - /build/utils/.*
  - /litmus-portal/backend/graphql-server/graph/generated/.*
  - /litmus-portal/frontend/.*/style\.ts
test:
  include:
    - /contribute/developer_guide/test_*\.py
