dist: trusty
sudo: required
install: true
language: go
go:
  - 1.11.x
env:
  global:
    - GOARCH=amd64
    - GO111MODULE=on
before_install:
  - sleep 15
  - sudo apt-get install -y
  - sudo apt-get install -y curl
script:
  - make godeps
  - make
