---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-chaos
  namespace: #{INFRA_NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaos-cluster-role
rules:
  # for managing the pods created by workflow controller to implement individual steps in the workflow
  - apiGroups: ['']
    resources: ['pods', 'services']
    verbs: ['create', 'get', 'watch', 'patch', 'delete', 'list']
  - apiGroups: ['']
    resources: ['namespaces']
    verbs: ['get', 'watch', 'patch', 'list']

  # for tracking & getting logs of the pods created by workflow controller to implement individual steps in the workflow
  - apiGroups: ['']
    resources: ['pods/log', 'pods/exec']
    verbs: ['get', 'watch', 'create', 'delete', 'patch']
  - apiGroups: ['']
    resources: ['secrets', 'configmaps']
    verbs: ['get', 'watch', 'create', 'patch']

  # for creation & deletion of application in predefined workflows
  - apiGroups: ['apps']
    resources: ['deployments']
    verbs: ['delete']
  - apiGroups: ['apps']
    resources: ['deployments', 'statefulsets']
    verbs: ['get', 'watch', 'patch' , 'create']

  # for creation, status polling and deletion of litmus chaos resources used within a chaos workflow
  - apiGroups: ["litmuschaos.io"]
    resources:
      ["chaosengines", "chaosexperiments", "chaosresults", "chaosschedules"]
    verbs: ["create", "list", "get", "patch", "delete", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chaos-cluster-role
subjects:
  - kind: ServiceAccount
    name: argo-chaos
    namespace: #{INFRA_NAMESPACE}