apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer-account
  namespace: litmus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: modify-deployments-to-sa
  namespace: litmus
subjects:
  - kind: ServiceAccount
    name: deployer-account
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: self-deployer
  namespace: litmus
  labels:
    component: self-deployer
spec:
  replicas: 1
  selector:
    matchLabels:
      component: self-deployer
  template:
    metadata:
      labels:
        component: self-deployer
    spec:
      containers:
        - name: deployer
          image: litmuschaos/litmusportal-self-deployer:ci
          imagePullPolicy: Always
          env:
            - name: SERVER
              value: http://litmusportal-server-service:8080
            - name: SELF_CLUSTER
              value: "true"
      serviceAccountName: deployer-account