---
user: "{{ lookup('env','GKEUSER') }}"
initial_node_count: 3
machine_type: n1-standard-2
disk_size_gb: 80
image_type: Ubuntu
zone: us-central1-a
project: openebs-ci
auth_kind: serviceaccount
ssh_key_fn: gke_ssh_key
ssh_user: gkeuser