kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: testclaim
  annotations:
    volume.beta.kubernetes.io/storage-class: testclass
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: jenkins
spec:
 replicas: 1
 template:
  metadata:
   labels:
    lkey: lvalue
  spec:
   securityContext:
     fsGroup: 1000
   containers:
   - name: jenkins
     imagePullPolicy: IfNotPresent
     image: jenkins/jenkins:lts
     ports:
     - containerPort: 8080
     volumeMounts:  
       - mountPath: /var/jenkins_home
         name: jenkins-home 
   volumes: 
     - name: jenkins-home
       persistentVolumeClaim: 
         claimName: testclaim
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  labels:
    lkey: lvalue
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    lkey: lvalue
  type: NodePort
