apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
  labels:
    lkey: lvalue
    affinity_label: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        lkey: lvalue
        affinity_label: jenkins
    spec:
      securityContext:
         fsGroup: 1000
      containers:
      - name: jenkins
        imagePullPolicy: IfNotPresent
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080
        volumeMounts:  
        - mountPath: /var/jenkins_home
          name: jenkins-home 
      volumes: 
      - name: jenkins-home
        persistentVolumeClaim: 
          claimName: testclaim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: testclaim
  labels:
    affinity_label: jenkins
spec:
  storageClassName: testclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: volume-capacity
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  labels:
    lkey: lvalue
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    lkey: lvalue
  type: NodePort
