---
apiVersion: batch/v1
kind: Job
metadata:
  name: litmus-jenkins
  namespace: litmus 
spec:
  template:
    metadata:
      name: litmus
      labels:
        app: jenkins-deployment-litmus
   
    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: openebs/ansible-runner
        imagePullPolicy: Always

        env: 
          - name: ANSIBLE_STDOUT_CALLBACK
            #value: log_plays, actionable, default
            value: default

          - name: PROVIDER_STORAGE_CLASS
            # Supported values: openebs-standard, local-storage
            value: openebs-standard

          - name: APP_PVC
            value: jenkins-claim

            # Application label
          - name: APP_LABEL
            value: 'app=jenkins-app'

            # Application namespace
          - name: APP_NAMESPACE
            value: litmus
 
        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./jenkins/deployers/test.yml -i /etc/ansible/hosts -v; exit 0"]
        
