---
- block:
   - name: Add Kubernetes yum repository
     yum_repository:
       name: Kubernetes
       description: Kube YUM repo
       baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64 
       gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
     become: true

   - name: Install RPM dependencies
     shell: "yum install -y yum-utils device-mapper-persistent-data lvm2 socat ebtables"
     become: true

   - name: Add docker repo
     shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
     become: true

   - name: Install RPM Packages
     shell: "yum install -y --setopt=obsoletes=0 docker-ce-17.03.0.ce-1.el7.centos docker-ce-selinux-17.03.0.ce-1.el7.centos"
     become: true

   - name: get-pip
     shell: "curl 'https://bootstrap.pypa.io/get-pip.py' -o 'get-pip.py'"
     become: true

   - name: Install pip
     shell: "python get-pip.py"
     become: true

   - name: Install RPM Packages
     yum:
       name: "{{ item }}" 
       state: present
     become: true
     with_items: "{{ k8s_rpm_packages }}"
  
   - name: Disable swap
     shell: |
       swapoff -a
       sed -i '/swap/s/^/#/g' /etc/fstab
       setenforce 0
       systemctl start docker && systemctl enable docker
     become: true

   - name: Install jq-devel
     yum:
       name: jq-devel
       state: present
     become: true

  when: build_type == "normal"

- name: Get Current User
  command: whoami
  register: user

- stat:
    path: "{{ k8s_images_path }}"
  register: status

- name: Create Directory
  file:
    path: "{{ k8s_images_path }}"
    state: directory
  become: true
  when: status.stat.isdir is not defined

- stat:
    path: "{{ k8s_images_path }}"
  register: status

- name: Change Folder Permissions
  file:
    path: "{{ k8s_images_path }}"
    owner: "{{ user.stdout }}"
    group: "{{ user.stdout }}"
    recurse: true
  become: true
  when: status.stat.isdir is defined and status.stat.isdir

- block:
   - name: Copy TAR to remote
     copy:
       src: "{{ k8s_images }}"
       dest: "{{ k8s_images_path }}"

   - name: Copy local rpm files to K8s-Master and K8s-Minions
     copy:
       src: "{{ item }}"
       dest: "{{ k8s_images_path }}"
     with_items: "{{ k8s_rpmd_packages }}"

  when: build_type == "normal"
