---
initial_node_count: 3
disk_size_gb: 80
ssh_user: ubuntu #Default user for Amazon Linux Images(AMI)
node_type: m5.xlarge
nodes_min: 3
nodes_max: 5
max_pods_per_node: 58
node_ami_family: Ubuntu1804
region: 
  - eu-north-1
  - eu-central-1
  - us-east-2
  - eu-west-1
