---
initial_node_count: 3
disk_size_gb: 80
region: us-west-2 # Currently EKS is mostly available on us-west-2 region
ssh_user: ec2-user #Default user for Amazon Linux Images(AMI)
node_type: m5.large
nodes_min: 3
nodes_max: 5
