---
apiVersion: batch/v1
kind: Job
metadata:
  name: cruncy-postgres-loadgen 
  namespace: litmus
spec:
  template:
    metadata:
      name: crunchy_postgres-loadgen
      namespace: litmus
    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      containers:
      - name: loadgen
        image: openebs/ansible-runner
        imagePullPolicy: Always
        env: 
        
          - name: ANSIBLE_STDOUT_CALLBACK
            #value: log_plays
            value: actionable

        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./crunchy-postgres/workload/test.yml -i /etc/ansible/hosts -v; exit 0"]
