# TODO 
# Apply openebs operator and openebs storage class

- hosts: localhost
  connection: local

  vars_files:
  - vars.yaml

  tasks:
    - name: Applying openebs operator
      shell: "{{ kubeapply }} apply -f {{ openebs_operator_link }}" 
      args:
        executable: /bin/bash

    - name: Applying openebs storageclass 
      shell: "{{ kubeapply }} apply -f {{ openebs_storageclass_link }}" 
      args:
        executable: /bin/bash

    - name: Applying openebs storagepoolclaim 
      shell: "{{ kubeapply }} apply -f {{ openebs_storagepoolclaim_link }}" 
      args:
        executable: /bin/bash

    - block:
          - set_fact:
              flag: "Pass"
      rescue: 
        - set_fact: 
            flag: "Fail"
