---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: litmus-pgset-
  namespace: litmus
spec:
  template:
    metadata:
      name: litmus
      labels:
        app: postgres-deployment-litmus

    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: openebs/ansible-runner:ci
        imagePullPolicy: Always

        env:
          - name: ANSIBLE_STDOUT_CALLBACK
            #value: log_plays, actionable, default
            value: default

          - name: PROVIDER_STORAGE_CLASS
            # Supported values: openebs-standard, local-storage
            value: openebs-standard

          - name: APP_PVC
            value: pgdata-claim

            # Application label
          - name: APP_LABEL
            value: 'app=pgset'

            # Application namespace
          - name: APP_NAMESPACE
            value: litmus

          - name: DEPLOY_TYPE
            value: statefulset

        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./crunchy-postgres/deployers/test.yml -i /etc/ansible/hosts -v; exit 0"]
