---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: percona-loadgen-
  namespace: litmus
spec:
  template:
    metadata:
      name: percona-loadgen
      namespace: litmus
      labels:
        loadgen: percona-loadjob
    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: openebs/ansible-runner:ci
        imagePullPolicy: Always
        env: 
          - name: ANSIBLE_STDOUT_CALLBACK
            #value: log_plays
            value: default
            
          - name: APP_LABEL
            value: name=percona

            #Namespace in which loadgen pod will be deployed
          - name: APP_NAMESPACE
            value: app-percona-ns 

          - name: APP_SERVICE_LABEL
            value: name=percona
            
          - name: LOADGEN_LABEL
            value: loadgen=percona-loadgen

            # Database user name
          - name: DB_USER
            value: root

          - name: DB_PASSWORD
            value: k8sDem0

        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./percona/workload/test.yml -i /etc/ansible/hosts -v; exit 0"]
