---
version: 2.1

executors:
  golang:
    docker:
      - image: circleci/golang:1.14.8-node

jobs:
  build-backend-services:
    executor: golang

    steps:
      - cd litmus-portal/backend/graphql-server
      - go build server.go