version: 2.1
jobs:
  build_test_push:
    machine: true
    working_directory: ~/go/src/github.com/litmuschaos/litmus
    environment:
      HOME: /home/circleci
      GOVERSION: 1.14.5
      OS: linux
      ARCH: amd64
      GO111MODULE: "on"
      NODE_VERSION: v12.0.0
    steps:
      - checkout
      # build and push the application image
      - run:
          name: Install Litmus Portal deps
          command: |
            set +e
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install ${NODE_VERSION}
            nvm alias default {NODE_VERSION}
            wget https://golang.org/dl/go${GOVERSION}.${OS}-${ARCH}.tar.gz
            sudo tar -C /usr/local -xzf go${GOVERSION}.${OS}-${ARCH}.tar.gz
            export PATH=$PATH:/usr/local/go/bin
      - run:
          name: Running Litmus Portal Makefile
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd litmus-portal && make all


workflows:
  version: 2
  litmus_portal_build_deploy:
    jobs:
      - build_test_push:
          filters:
            tags:
              only: /.*/