version: 2
jobs:
    build:
        machine: true
        steps:
            - checkout

            # build the application image
            - run: |
                  echo "$DPASS" | docker login --username $DUNAME --password-stdin
                  cd litmus-portal && make build push
