---
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: #{AGENT-NAMESPACE}
data:
  config: |
    containerRuntimeExecutor: k8sapi
    executor:
      imagePullPolicy: Always