---
- name: Obtain list of existing namespaces
  k8s_facts:
    kind: Namespace
  register: ns_list
 
- debug: 
    msg: "{{item.metadata.name}}"
  with_items: "{{ns_list.resources}}"

- name: Create test specific namespace.
  k8s:
    kind: Namespace
    name: "{{ app_ns }}"
    state: present
  when: app_ns != 'litmus' and app_ns not in item.metadata.name
  with_items: "{{ ns_list.resources }}"

- include_tasks: /utils/k8s/status_testns.yml

