---
apiVersion: batch/v1
kind: Job
metadata:
  name: litmus-cassandra-loadgen
  namespace: litmus 
spec:
  template:
    metadata:
      name: litmus
      labels:
        loadgen: cassandra-loadjob

    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: openebs/ansible-runner:ci
        imagePullPolicy: Always
        env: 
          - name: ANSIBLE_STDOUT_CALLBACK
            #value: log_plays
            value: default

          - name: LOADGEN_NS
            value: litmus

          - name: LOADGEN_LABEL
            value: 'loadgen=cassandra-loadgen'

        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./cassandra/workload/test.yml -i /etc/ansible/hosts -v; exit 0"]        
