---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: litmus-openebs-helm-
  namespace: litmus
spec:
  template:
    metadata:
      name: litmus
      labels:
        app: openebs-helm

    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: openebs/ansible-runner:ci
        imagePullPolicy: Always

        env:
          - name: ANSIBLE_STDOUT_CALLBACK
            #value: log_plays, actionable, default
            value: default

          - name: NAMESPACE
            value: openebs

        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./providers/openebs/installers/openebs_helm/test.yml -i /etc/ansible/hosts -v; exit 0"]

