---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: ansible-loop
  namespace: litmus
spec:
  template:
    metadata:
      labels:
        name: openebs-pool-failure
    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: openebs/ansible-runner:ci
        env:
          - name: ANSIBLE_STDOUT_CALLBACK
            #value: log_plays
            #value: actionable
            value: default

          - name: APP_NAMESPACE
            value: percona-cstor

          - name: APP_LABEL
            value: 'name=percona'

          - name: APP_PVC
            value: percona-mysql-claim

          - name: LIVENESS_APP_LABEL
            value: ""

          - name: LIVENESS_APP_NAMESPACE
            value: ""

        command: ["/bin/bash"]
        args: ["-c", "sleep 10000"]
        volumeMounts:
          - name: litmuspath
            mountPath: /litmus
        tty: true
      volumes:
        - name: litmuspath
          hostPath:
            path: /home/prateek/openebs/litmus

