---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-liveness-check
  labels:
    liveness_lkey: liveness_lvalue
spec:

  restartPolicy: Never

  #affinity:
  #  podAffinity: # (/podAntiAffinity)
  #    requiredDuringSchedulingIgnoredDuringExecution:
  #    - labelSelector:
  #        matchExpressions:
  #        - key: name
  #          operator: In
  #          values: 
  #          - litmus # (/percona) 
  #      topologyKey: kubernetes.io/hostname

  containers:
  - name: mysql-liveness-check
    image: openebs/tests-mysql-client
    command: ["/bin/bash"]
    args: ["-c", "bash mysql-liveness-check.sh db-cred.cnf ; exit 0"]
    tty: true 
    volumeMounts:
      - mountPath: /db-cred.cnf
        subPath: db-cred.cnf
        name: db-cred
  volumes:
    - name: db-cred
      configMap:
        name: db-cred  
