---
- hosts: localhost

  vars_files:
    - vars.yml
  

  tasks:
    - block:

        - name: Terminate instances that were previously launched
          ec2:
            state: 'absent'
            wait: yes
            instance_ids: "{{ item }}"
            region: "{{ region }}"
          with_lines: cat ./ec2-id 

        - name: Deleting Route Table and Route
          ec2_vpc_route_table:
            route_table_id: "{{ route_table_id }}"
            lookup: id
            state: absent
            vpc_id: "{{ vpc_id }}"
            region: "{{ region }}"
            subnets:
              - "{{ subnet_id }}"
            routes:
              - dest: "{{ destination_cidr }}"
                gateway_id: "{{ gateway_id }}"   
            purge_routes: yes
            purge_subnets: yes
            purge_tags: yes

        - name: Deleting Internet gateway
          ec2_vpc_igw:
            vpc_id: "{{ vpc_id }}"
            region: "{{ region }}"
            state: absent        

        - name: Deleting subnet 
          ec2_vpc_subnet:
            state: absent
            vpc_id: "{{ vpc_id }}"
            cidr: "{{ cidr_block2 }}"
            region: "{{ region }}"
            purge_tags: yes

        - name: Deleting key-pair
          ec2_key:
           state: 'absent'
           name: openshift_keypair
           region: "{{ region }}"   

        - name: Delete Security Group
          ec2_group:
           name: Web DMZ
           description: DMZ Security Group
           state: 'absent'
           vpc_id: "{{ vpc_id }}"
           region: "{{ region }}"
                  
        - name: Deleting VPC
          ec2_vpc_net:
            name: "{{ vpc_name }}"
            cidr_block: "{{ cidr_block }}"
            region: "{{ region }}"
            state: 'absent' 
            purge_cidrs: yes  

        - name: Deleting temporary files
          shell: rm ec2-id id.csv vol-id dns.csv ip.csv openshift.ppk --force    

            
             
 

        

