# Create an OSEv3 group that contains the masters, nodes, and etcd groups
[OSEv3:children]
masters
nodes
etcd

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
openshift_disable_check=disk_availability,memory_availability
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=root
# Deployment type: origin or openshift-enterprise
openshift_deployment_type=origin
# Resolvable domain (for testing you can use external ip of the master node)
openshift_master_default_subdomain=master_pub_dns
openshift_hosted_manage_registry=true
openshift_hosted_manage_router=true
openshift_router_selector='node-role.kubernetes.io/infra=true'
openshift_registry_selector='node-role.kubernetes.io/infra=true'
openshift_master_api_port=443
# External ip of the master node
openshift_master_cluster_hostname=master_pub_dns
# External ip of the master node
openshift_master_cluster_public_hostname=master_pub_dns
openshift_master_console_port=443
openshift_docker_insecure_registries=172.30.0.0/16
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]

# host group for masters
[masters]
master_pub_ip
# host group for etcd
[etcd]
master_pub_ip
# host group for nodes, includes region info
[nodes]
master_pub_ip openshift_node_group_name='node-config-master' 
node1_pub_ip openshift_node_group_name='node-config-compute'
node2_pub_ip openshift_node_group_name='node-config-compute'
node3_pub_ip openshift_node_group_name='node-config-infra'