---
region: us-east-1
cidr_block: 10.0.0.0/16
cidr_block2: 10.0.1.0/24
destination_cidr: 0.0.0.0/0
image_ami: ami-9887c6e7   #centos
instance_size: t2.xlarge
node_count: 4
subnet_name: openshift-subnet
igw_name: traffic-igw
ec2_key_directory: "./"
route_table_id: "{{ lookup('lines', 'grep route_table_id ./id.csv | cut -d, -f5 | cut -d: -f2') }}"
gateway_id: "{{ lookup('lines', 'grep gateway_id ./id.csv | cut -d, -f4 | cut -d: -f2') }}"
subnet_id: "{{ lookup('lines', 'grep subnet_id ./id.csv | cut -d, -f3 | cut -d: -f2') }}"
vpc_name: "{{ lookup('lines', 'grep vpc_name ./id.csv | cut -d, -f2 | cut -d: -f2') }}"
vpc_id: "{{ lookup('lines', 'grep vpc_id ./id.csv | cut -d, -f1 | cut -d: -f2') }}"
