---
apiVersion: batch/v1
kind: Job
metadata:
  name: litmus-openebs-setup
  namespace: litmus 
spec:
  template:
    metadata:
      name: litmus
      labels: 
        provider: openebs-setup
    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: openebs/ansible-runner:ci
        imagePullPolicy: Always
        env: 
          - name: mountPath
            value: /mnt/openebs
          - name: ANSIBLE_STDOUT_CALLBACK
            value: default
          - name: OPENEBS_VERSION
            value: master
          - name: MAYA_APISERVER_IMAGE
            value:
          - name: OPENEBS_PROVISIONER_IMAGE
            value:
          - name: OPENEBS_SNAPSHOT_CONTROLLER_IMAGE
            value:
          - name: OPENEBS_SNAPSHOT_PROVISIONER_IMAGE
            value:
          - name: OPENEBS_IO_JIVA_CONTROLLER_IMAGE
            value:
          - name: OPENEBS_IO_JIVA_REPLICA_IMAGE
            value:
          - name: OPENEBS_IO_VOLUME_MONITOR_IMAGE
            value:
          - name: OPENEBS_IO_JIVA_REPLICA_COUNT
            value:
          - name: NODE_DISK_MANAGER_IMAGE
            value:
          - name: OPENEBS_IO_CSTOR_TARGET_IMAGE
            value:
          - name: OPENEBS_IO_CSTOR_POOL_IMAGE
            value:
          - name: OPENEBS_IO_CSTOR_POOL_MGMT_IMAGE
            value:
          - name: OPENEBS_IO_CSTOR_VOLUME_MGMT_IMAGE
            value:        
          - name: OPENEBS_IO_CSTOR_POOL_EXPORTER_IMAGE
            value:  
          - name: IMAGE_PULL_POLICY
            value:
          - name: OPENEBS_INFRA_CHAOS
            value: 
          - name: RUN_ID
            value:   
          - name: SPARSE_FILE_COUNT
            value: "10" 
          - name: INSTALL_DEFAULT_CSP
            value:      
        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./providers/openebs/installers/operator/master/ansible/openebs_setup.yaml -i /etc/ansible/hosts -vv; exit 0"]
        volumeMounts:
          - name: kubeconfig 
            mountPath: /root/admin.conf
            subPath: admin.conf
          - name: logs
            mountPath: /var/log/ansible 
      volumes: 
        - name: kubeconfig
          configMap: 
            name: kubeconfig 
        - name: logs 
          hostPath:
            path: /mnt/openebs
            type: ""
