---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: avalanche
  labels:
    lkey: lvalue
    system: freshtracks
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        avalanche/scrape: "true"
      labels:
        lkey: lvalue
        system: freshtracks
    spec:
      containers:
      - name: avalanche
        image: quay.io/freshtracks.io/avalanche
        imagePullPolicy: IfNotPresent
        args:
        - --metric-count=10
        - --series-count=5
        - --port=9001
        ports:
        - containerPort: 9001
          protocol: TCP
          name: metrics

      