---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: prometheus
  labels:
    lkey: lvalue
    openebs.io/target-affinity: prometheus
spec:
  replicas: 1
  selector: 
    matchLabels:
      lkey: lvalue
  template: 
    metadata:
      labels: 
        lkey: lvalue
        openebs.io/target-affinity: prometheus
    spec:
      containers:
        - resources:
            limits:
              cpu: 0.5
          name: prometheus
          image: prom/prometheus
          imagePullPolicy: IfNotPresent 
          #args:
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: k8sDem0
          ports:
            - containerPort: 9000
              name: prometheus
          volumeMounts:
            - mountPath: /etc/prometheus/conf
              name: data-vol
      volumes:
        - name: data-vol
          persistentVolumeClaim:
            claimName: testclaim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: testclaim
  labels: 
    openebs.io/target-affinity: prometheus  
spec:
  storageClassName: openebs-mongodb
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    lkey: lvalue
spec:
  ports:
    - port: 9090
      targetPort: 9090
  selector:
      lkey: lvalue
