# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
 name: mongo
 labels:
   lkey: lvalue
spec:
 ports:
 - port: 27017
   targetPort: 27017
 clusterIP: None
 selector:
   role: mongo
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
 name: mongo
 labels: 
   lkey: lvalue
   openebs.io/target-affinity: mongo 
spec:
 serviceName: "mongo"
 replicas: 2
 template:
   metadata:
     labels:
       lkey: lvalue
       role: mongo
       openebs.io/target-affinity: mongo
       environment: test
   spec:
     terminationGracePeriodSeconds: 10
     containers:
       - name: mongo
         image: mongo
         command:
                 #    - mongod
                 #    - "--replSet"
                 #    - rs0
                 #    - "--smallfiles"
                 #    - "--noprealloc"
                 #    - "--bind_ip_all"
         ports:
           - containerPort: 27017
         volumeMounts:
           - name: testclaim
             mountPath: /data/db
       - name: mongo-sidecar
         image: cvallance/mongo-k8s-sidecar
         env:
           - name: MONGO_SIDECAR_POD_LABELS
             value: "role=mongo,environment=test"
 volumeClaimTemplates:
 - metadata:
     name: testclaim
     labels: 
       openebs.io/target-affinity: mongo
   spec:
     storageClassName: testclass
     accessModes:
       - ReadWriteOnce
     resources:
       requests:
         storage: volume-capacity
