---
apiVersion: batch/v1
kind: Job
metadata:
  name: litmus-mongodb
  namespace: litmus 
spec:
  template:
    metadata:
      name: litmus
      labels:
        app: mongodb-deployment-litmus
   
    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: openebs/ansible-runner
        imagePullPolicy: Always

        env: 
          - name: ANSIBLE_STDOUT_CALLBACK
            #value: log_plays
            value: default

          - name: PROVIDER_STORAGE_CLASS
            # Supported values: openebs-standard, local-storage
            value: openebs-mongodb

          - name: PROVIDER_PVC
            value: openebs-mongodb
 
        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./mongodb/deployers/test.yml -i /etc/ansible/hosts -v; exit 0"]
        
