---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: openebs-target-network-delay- 
  namespace: litmus 
spec:
  template:
    metadata:
      labels:
        name: litmus 
    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: openebs/ansible-runner
        env: 
          - name: ANSIBLE_STDOUT_CALLBACK
            #value: log_plays
            #value: actionable
            value: default
 
          - name: APP_NAMESPACE
            value: "percona"

          - name: APP_LABEL
            value: "name=percona"

          - name: APP_PVC
            value: "percona-mysql-claim"

          - name: NETWORK_DELAY
            value: "3000" # in milliseconds

          - name: CHAOS_DURATION
            value: "60" # in seconds

        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./percona/chaos/openebs_target_network_delay/test.yaml -i /etc/ansible/hosts -vv; exit 0"]
        volumeMounts:
          - name: logs 
            mountPath: /var/log/ansible 
        tty: true
      - name: logger
        image: openebs/logger
        command: ["/bin/bash"]
        args: ["-c", "./logger.sh -d 10 -r maya,openebs,pvc,percona; exit 0"] 
        volumeMounts:
          - name: kubeconfig 
            mountPath: /root/admin.conf
            subPath: admin.conf
          - name: logs
            mountPath: /mnt 
        tty: true 
      volumes: 
        - name: kubeconfig
          configMap: 
            name: kubeconfig 
        - name: logs 
          hostPath:
            path: /mnt/chaos/openebs_target_network_delay
            type: ""

