---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: cstor-storage-policies-
  namespace: litmus
spec:
  template:
    metadata:
      name: litmus
      labels:
        app: cstor-storage-policy

    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: openebs/ansible-runner:ci
        imagePullPolicy: Always

        env:
          - name: ANSIBLE_STDOUT_CALLBACK
            #value: log_plays, actionable, default
            value: default

            # Provide name POOL_NAME for the cstor-pool
          - name: POOL_NAME
            value: cstor-sparse-pool

            # The path where the local pv can be created
          - name: POOL_PATH
            value: "/var/openebs/local"

            ## two values: create and delete 
          - name: ACTION
            value: create

        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./providers/cstor-storage-policies/test.yml -i /etc/ansible/hosts -v; exit 0"]
