---
apiVersion: batch/v1
kind: Job
metadata:
  name: litmus-jupyter-loadgen
  namespace: litmus 
spec:
  template:
    metadata:
      name: litmus
    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      containers:
      - name: loadgen
        image: vvibhr995/loadgen-jupyter:jiva
        imagePullPolicy: Always
        env: 
          - name: ANSIBLE_STDOUT_CALLBACK
            #value: log_plays
            value: actionable
        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./jupyter/workload/test.yml -i /etc/ansible/hosts -v; exit 0"]
        
