---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: litmus-namespace-scope
  namespace: #{AGENT-NAMESPACE}
  labels:
    name: litmus-namespace-scope
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: litmus-namespace-scope
  namespace: #{AGENT-NAMESPACE}
  labels:
    name: litmus-namespace-scope
rules:
  - apiGroups: [""]
    resources: ["replicationcontrollers","secrets"]
    verbs: ["get","list"]
  - apiGroups: ["apps.openshift.io"]
    resources: ["deploymentconfigs"]
    verbs: ["get","list"]
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
    verbs: ["get","list"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get","list","deletecollection"]
  - apiGroups: ["argoproj.io"]
    resources: ["rollouts"]
    verbs: ["get","list"]
  - apiGroups: [""]
    resources: ["pods","configmaps","events","services"]
    verbs: ["get","create","update","patch","delete","list","watch","deletecollection"]
  - apiGroups: ["litmuschaos.io"]
    resources: ["chaosengines","chaosexperiments","chaosresults"]
    verbs: ["get","create","update","patch","delete","list","watch","deletecollection"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: litmus-namespace-scope
  namespace: #{AGENT-NAMESPACE}
  labels:
    name: litmus-namespace-scope
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: litmus-namespace-scope
subjects:
  - kind: ServiceAccount
    name: litmus-namespace-scope
    namespace: #{AGENT-NAMESPACE}