---
k8s_rpm_packages:
  - epel-release
  - unzip
  - curl
  - wget
  - socat
  - ebtables

k8s_images_path: "{{ ansible_env.HOME}}/setup/k8s"
k8s_conf: k8s.conf
sysctl_path: /etc/sysctl.d/
k8s_images: k8s_images_{{ k8s_version }}.tar

k8s_rpmd_packages:
  - kubeadm.rpm
  - kubectl.rpm
  - kubelet.rpm 
  - kubernetes-cni.rpm

