---
- hosts: localhost
  connection: local

  vars_files:
    - test_vars.yml

  tasks:
    - block:

        ## Generating the testname for deployment
        - include_tasks: /common/utils/create_testname.yml

        ## RECORD START-OF-TEST IN LITMUS RESULT CR
        - include_tasks: /common/utils/update_litmus_result_resource.yml
          vars:
            status: 'SOT'

        ## Actual Test to deploy Jupyter NoteBook on k8s
        ## Creating namespaces and making the application for deployment
        - include_tasks: /common/utils/pre_create_app_deploy.yml

        ## Deploying the application
        - include_tasks: /common/utils/deploy_single_app.yml
          vars:
          delay: 60
          retries: 20

        - set_fact:
           flag: "Pass"

      rescue:
        - set_fact:

            flag: "Fail"
      always:
            ## RECORD END-OF-TEST IN LITMUS RESULT CR
        - include_tasks: /common/utils/update_litmus_result_resource.yml
          vars:
            status: 'EOT'