---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: node-replacement-
  namespace: litmus
spec:
  template:
    metadata:
      labels:
        name: node-replacement
    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      #nodeSelector:
      #  kubernetes.io/hostname:

      tolerations:
      - key: "infra-aid"
        operator: "Equal"
        value: "observer"
        effect: "NoSchedule"

      containers:
      - name: ansibletest
        image: openebs/ansible-runner:ci
        imagePullPolicy: Always
        env:
          - name: ANSIBLE_STDOUT_CALLBACK
            #value: log_plays
            #value: actionable
            value: default

          - name: APP_NAMESPACE
            value: app-percona-ns

          - name: APP_PVC
            value: percona-mysql-claim

          - name: APP_LABEL
            value: 'name=percona'

          - name: LIVENESS_APP_LABEL
            value: "liveness=percona-liveness"

          - name: LIVENESS_APP_NAMESPACE
            value: "litmus"

          - name: DATA_PERSISTENCY
            value: "enable"

          - name: PLATFORM
            value: "AWS"

          ## Value of AWS_ACCESS_KEY_ID need to be replaced with original value
          - name: AWS_ACCESS_KEY_ID
            value: "access_key"

          ## Value of AWS_SECRET_ACCESS_KEY need to be replaced with original value
          - name: AWS_SECRET_ACCESS_KEY
            value: "secret_key"

          ## Actions can be performed on AWS ec2 instance and values (stopped,running,present,absent,restarted ansible-version >= 2.2)
          - name: ACTION
            value: "stopped"

          - name: SUBNET_ID
            value: "subnet_id"

        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./percona/chaos/app_node_failure_ups_diff_name/test.yml -i /etc/ansible/hosts -vv; exit 0"]
        volumeMounts:
          - name: logs
            mountPath: /var/log/ansible
        tty: true

      - name: logger
        image: openebs/logger
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          # spec.volumes is not supported via downward API
          - name: MY_POD_HOSTPATH
            value: /mnt/chaos/node-replacement
        command: ["/bin/bash"]
        args: ["-c", "./logger.sh -d ansibletest -r maya,openebs,pvc,percona; exit 0"]
        volumeMounts:
          - name: kubeconfig
            mountPath: /root/admin.conf
            subPath: admin.conf
          - name: logs
            mountPath: /mnt
        tty: true
      volumes:
        - name: kubeconfig
          configMap:
            name: kubeconfig
        - name: logs
          hostPath:
            path: /mnt/chaos/node-replacement
            type: ""

