---
apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-loadgen 
  namespace: litmus
spec:
  template:
    metadata:
      name: mongodb-loadgen
      namespace: litmus
    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      containers:
      - name: loadgen
        image: ranjnshashank855/mongo-load:test
        imagePullPolicy: Always
        env: 
          - name: ANSIBLE_STDOUT_CALLBACK
            #value: log_plays
            value: actionable
        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./mongodb/workload/test.yml -i /etc/ansible/hosts -v; exit 0"]