---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: mongodb-loadgen -
  namespace: litmus
spec:
  template:
    metadata:
      name: mongodb-loadgen
      namespace: litmus
      labels:
        loadgen: mongodb-loadjob
    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: openebs/ansible-runner:ci
        imagePullPolicy: Always
        env: 
          - name: ANSIBLE_STDOUT_CALLBACK
            #value: log_plays
            value: default

          - name: POD_NAME
            value: mongo-0

          - name: SERVICE_NAME 
            value: mongo

          - name: LOADGEN_LABEL
            value: loadgen=mongo-loadgen

          - name: DATABASE_NAME
            value: sbtest

        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./mongodb/workload/test.yml -i /etc/ansible/hosts -v; exit 0"]
