---
## K8S-LOCALHOST PREPARATION

- name: Install RPM dependencies
  shell: "yum install -y yum-utils device-mapper-persistent-data lvm2 socat ebtables"
  become: true
  delegate_to: 127.0.0.1

- name: Add docker repo
  shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
  become: true
  delegate_to: 127.0.0.1

- name: Install RPM Packages
  shell: "yum install -y docker-ce-17.03.0.ce-1.el7.centos docker-ce-selinux-17.03.0.ce-1.el7.centos" 
  become: true
  delegate_to: 127.0.0.1

- name: get-pip
  shell: "curl 'https://bootstrap.pypa.io/get-pip.py' -o 'get-pip.py'"
  become: true
  delegate_to: 127.0.0.1

- name: Install pip
  shell: "python get-pip.py"
  become: true
  delegate_to: 127.0.0.1

- name: Install PIP Packages
  pip:
    name: "{{ item }}"
    state: present
  with_items: "{{ pip_local_packages }}"
  delegate_to: 127.0.0.1
  become: true

## Common preparation tasks

- name: Create files directory in kubernetes role
  file:
    path: "{{ playbook_dir }}/roles/{{item}}/files"
    state: directory
    mode: 0755
  with_items:
    - kubernetes
    - k8s-master
    - k8s-hosts

## kubernetes role preparation

- name: Get .rpm package details
  shell: curl -sS https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/primary.xml | grep -- -{{ k8s_version }} | grep "location href" | awk '{print $2}' | cut -d '/' -f4 | cut -d '"' -f1
  register: k8s_rpm_packages

- name: Get .rpm kubernetes packages google cloud 
  get_url: 
    url: "https://packages.cloud.google.com/yum/pool/{{ item.0 }}"
    dest: "{{ playbook_dir }}/roles/kubernetes-centos/files/{{item.1}}"
    force: yes
  register: result
  until:  "'OK' in result.msg"
  delay: 5
  retries: 3
  with_together: 
    - "{{ k8s_rpm_packages.stdout_lines }}"
    - "{{ k8s_rpm_package_alias }}"

- name: Get CNI .rpm package from google cloud
  get_url:
    url: "{{k8s_cni_rpm_package}}"
    dest: "{{ playbook_dir }}/roles/kubernetes-centos/files/kubernetes-cni.rpm"
    force: yes
  register: result
  until: "'OK' in result.msg"
  delay: 5
  retries: 3

- name: Check whether rpm packages and images are already downloaded
  stat: 
    path: "{{ playbook_dir }}/roles/kubernetes-centos/files/k8s_images_{{ k8s_version }}.tar"
  register: stat_result

- block:
    - name: Start and Enable docker
      shell: "systemctl start docker && systemctl enable docker"
      become: true

    - name: Fetch K8s images from gcr.io/google_containers
      docker_image: 
        name: "{{item}}"
        state: present
        pull: true
        force: yes
      register: result
      until: "'Pulled image' and item in result.actions[0]"
      delay: 60
      retries: 3  
      with_items: "{{ k8s_images }}"
      become: true

    - name: Print K8s image names
      shell: printf "{{ item }}\n" >> imagelist.tmp
      with_items: "{{ k8s_images }}"

    - name: TAR the K8s images 
      shell: docker save $(cat imagelist.tmp) -o k8s_images_{{ k8s_version }}.tar
      become: true

    - name: Remove the .tmp file created to hold image list
      file: path="{{playbook_dir}}/imagelist.tmp" state=absent

    - name: Move K8s_images_{{ k8s_version }}.tar into kubernetes role
      shell: mv {{playbook_dir}}/k8s_images_{{ k8s_version }}.tar {{ playbook_dir }}/roles/kubernetes-centos/files
      become: true

    - name: Remove K8s images from K8s-localhost
      docker_image:
        name: "{{ item }}" 
        state: absent
      with_items: "{{ k8s_images }}"
      become: true
  
  when: stat_result.stat.exists == false 

## K8S-MASTER ROLE PREPARATION

- name: Get Log Aggregator
  get_url:
    url: "{{k8s_log_aggregator_url}}"
    dest: "{{ playbook_dir }}/roles/k8s-master-centos/files/{{k8s_log_aggregator}}"
    force: yes
  register: result
  until: "'OK' in result.msg"
  delay: 5
  retries: 3

- name: Fetch configure_K8s scripts into k8s-master role
  get_url: 
    url: "{{ item }}"
    dest: "{{ playbook_dir }}/roles/k8s-master-centos/files"
    force: yes
  register: result
  until:  "'OK' in result.msg"
  delay: 5
  retries: 3 
  with_items: "{{ k8s_master_scripts }}"

- name: Change Kubernetes version in configure scripts
  replace:
    path: "{{ playbook_dir }}/roles/k8s-master-centos/files/configure_k8s_master.sh"
    regexp: "kubeversion=\"v[1-9].[0-9].[0-9]\""
    replace: "kubeversion=\"v{{ k8s_version }}\""

- block: 
    - name: Fetch weave images from dockerhub
      docker_image:
        name: "{{ item }}"
        state: present
        pull: true
        force: yes
      register: result
      until: "'Pulled image' and item in result.actions[0]"
      delay: 60
      retries: 3
      with_items: "{{ weave_images }}" 
      become: true

    - name: Print weave image names
      shell: printf "{{ item }}\n" >> imagelist.tmp
      with_items: "{{ weave_images }}"

    - name: TAR the weave images
      shell: docker save $(cat imagelist.tmp) -o weave_images_{{ weave_version }}.tar
      become: true

    - name: Remove the .tmp file created to hold image list
      file: path="{{playbook_dir}}/imagelist.tmp" state=absent

    - name: Move weave_images_{{ weave_version }}.tar into k8s-master role
      shell: mv {{playbook_dir}}/weave_images_{{ weave_version }}.tar {{ playbook_dir }}/roles/k8s-master-centos/files
      become: true

    - name: Remove weave images from K8s-localhost
      docker_image:
        name: "{{ item }}" 
        state: absent
      with_items: "{{ weave_images }}"
      become: true
  
  when: stat_result.stat.exists == false

- name: Fetch the weave .yaml template from GitHub
  get_url:
    url: "{{ weave_template_link }}"
    dest: "{{ playbook_dir }}/roles/k8s-master-centos/files"
    force: yes
  register: result
  until:  "'OK' in result.msg"
  delay: 5
  retries: 3

## K8S-HOSTS ROLE PREPARATION

- name: Fetch configure_K8s scripts into k8s-host role
  get_url:
    url: "{{ item }}"
    dest: "{{ playbook_dir }}/roles/k8s-hosts-centos/files"
    force: yes
  register: result
  until:  "'OK' in result.msg"
  delay: 5
  retries: 3 
  with_items: "{{ k8s_host_scripts }}"

- name: Get Current User
  command: whoami 
  register: user

- name: Change Folder Permissions
  file:
    path: "{{ item }}"
    owner: "{{ user.stdout }}"
    group: "{{ user.stdout }}"
    recurse: true
  become: true
  with_items:
    - "{{ playbook_dir }}/roles/k8s-hosts-centos/files"
    - "{{ playbook_dir }}/roles/k8s-master-centos/files"
    - "{{ playbook_dir }}/roles/kubernetes-centos/files"
