---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: te-1
  labels:
    app: nuodb
    group: nuodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nuodb
  template:
    metadata:
      labels:
        app: nuodb
    spec:
      containers:
        - resources:
            limits:
              cpu: 0.5
          name: te
          image: nuodb/nuodb-ce:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - { name: DB_NAME,             value: "testdb" }
          - { name: NUOCMD_API_SERVER,   value: "admin.default.svc:8890"}
          - { name: PEER_ADDRESS,        value: "admin.default.svc" }
            #- { name: NUODB_LABELS,        value: "app=nuodb" }
          - { name: NUODB_OPTIONS,       value: "mem 0.5g" }
          args: [ "nuote", "--servers-ready-timeout", "300", "--database-created-timeout", "300" ]
          ports:
          - containerPort: 48006
            protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: demo-vol1
      volumes:
        - name: demo-vol1
          persistentVolumeClaim:
            claimName: demo-vol1-claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-vol1-claim
spec:
  storageClassName: openebs-standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
