---
apiVersion: v1
kind: Service
metadata:
  annotations:
      description: |
        Headless service permitting us to retrieve DNS A records that point directly to the pods backing the service.
      "service.alpha.kubernetes.io/tolerate-unready-endpoints": "true"
  name: domain
  labels:
    app: nuodb
    group: nuodb
spec:
  clusterIP: None
  ports:
  - { name: 8890-tcp,   port: 8890,   protocol: TCP,  targetPort: 8890  }
  - { name: 48004-tcp,  port: 48004,  protocol: TCP,  targetPort: 48004 }
  - { name: 48005-tcp,  port: 48005,  protocol: TCP,  targetPort: 48005 }
  selector:
    dns: domain
---
apiVersion: v1
kind: Service
metadata:
  annotations:
      description: "Service for Admin pods."
  labels:
    app: nuodb
    group: nuodb
  name: admin
spec:
  ports:
  - { name: 8890-tcp,   port: 8890,   protocol: TCP,  targetPort: 8890  }
  - { name: 48004-tcp,  port: 48004,  protocol: TCP,  targetPort: 48004 }
  - { name: 48005-tcp,  port: 48005,  protocol: TCP,  targetPort: 48005 }
  selector:
    app: admin


