---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sm
  labels:
    app: nuodb
    group: nuodb
spec:
  serviceName: sm
  replicas: 1
  selector:
    matchLabels:
      nodetype: sm
      database: "testdb"
      app: sm
      group: nuodb
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        nodetype: sm
        database: "testdb"
        app: sm
        group: nuodb
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        nodetype: sm
        database: "testdb"
        app: sm
        group: nuodb
    spec:
      containers:
      - name: sm
        image: nuodb/nuodb-ce:latest
        imagePullPolicy: IfNotPresent
        args: [ "nuosm", "--servers-ready-timeout", "300" ]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - { name: NUOCMD_API_SERVER,   value: "admin.litmus.svc:8888"}
        - { name: PEER_ADDRESS,        value: "admin.litmus.svc" }
        - { name: NUODB_OPTIONS,       value: "mem 0.5g" }
        ports:
        - containerPort: 48006
          protocol: TCP
        resources:
          requests:
            memory: "0.5Gi"
            cpu: "1"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File

