---
apiVersion: batch/v1
kind: Job
metadata:
  name: elasticsearch-loadgen
spec:
  template:
    metadata:
      name: elasticsearch-loadgen
      labels:
        loadgen_lkey: loadgen_lvalue
    spec:
      restartPolicy: Never
      containers:
      - name: elasticsearch-loadgen
        image: vvibhr995/elastic-load:latest
        command: [ "/bin/bash"]
        args: ["-c" ,"./elasticsearch-stress-test.py --es_address elasticsearch-logging-0.elasticsearch-logging  --indices 1 --documents 2 --seconds 120 --not-green --clients 3 --forever --no-cleanup"]
        tty: true 

