---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: |
      Headless service permitting us to retrieve DNS A records that point directly to the pods backing the service.
    "service.alpha.kubernetes.io/tolerate-unready-endpoints": "true"
  labels:
    group: nuodb
    app: domain
  name: domain
spec:
  clusterIP: None
  ports:
  - { name: 8888-tcp,   port: 8888,   protocol: TCP,  targetPort: 8888  }
  - { name: 48004-tcp,  port: 48004,  protocol: TCP,  targetPort: 48004 }
  - { name: 48005-tcp,  port: 48005,  protocol: TCP,  targetPort: 48005 }
  selector:
    dns: domain
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: "Service (and load-balancer) for Admin pods."
  labels:
    group: nuodb
    app: domain
    subgroup: admin
  name: a
spec:
  ports:
  - {name: 8888-tcp,  port: 8888,  protocol: TCP, targetPort: 8888}
  - {name: 48004-tcp, port: 48004, protocol: TCP, targetPort: 48004}
  - {name: 48005-tcp, port: 48005, protocol: TCP, targetPort: 48005}
  selector:
    app: a
  sessionAffinity: None
  type: LoadBalancer