---
- hosts: localhost
  connection: local

  vars_files:
    - test_vars.yml

  tasks:
    - block:

          ## PRE-CHAOS APPLICATION LIVENESS CHECK
        - include_tasks: /common/utils/application_liveness_check.yml
          when: liveness_label != ''

        ## RECORD START OF THE TEST IN LITMUS RESULT CR
        - include_tasks: /common/utils/create_testname.yml 

        - include_tasks: /common/utils/update_litmus_result_resource.yml
          vars:
            status: 'SOT'
            chaostype: "{{ test_name }}"

        ## DISPLAY APP INFORMATION 
 
        - name: Display the app information passed via the test job
          debug: 
            msg: 
              - "The application info is as follows:"
              - "Namespace           : {{ namespace }}"
              - "Target Namespace    : {{ target_namespace }}"
              - "Label               : {{ label }}"
              - "PVC                 : {{ pvc }}"  

        ## PRE-CHAOS APPLICATION LIVENESS CHECK

        - name: Verify that the AUT (Application Under Test) is running 
          include_tasks: /common/utils/status_app_pod.yml
          vars:
            application_name: "Percona"
            app_ns: "{{ namespace }}"
            app_lkey: "{{ label.split('=')[0] }}"
            app_lvalue: "{{ label.split('=')[1] }}"
            delay: '2'
            retries: '60'
  
        ## STORAGE FAULT INJECTION 

        - include: "/chaoslib/openebs/cstor_pool_network.yml"
          vars:
            ns: "{{ namespace }}"
            app_label: "{{ label }}"
            target_ns: "{{ target_namespace }}"
            chaos_duration: "{{ lookup('env','CHAOS_DURATION') }}"
            pvc_name: "{{ pvc }}"
          

        ## POST-CHAOS APPLICATION LIVENESS CHECK

        - name: Verify AUT liveness post fault-injection
          include_tasks: /common/utils/status_app_pod.yml
          vars:
            application_name: "Percona"
            app_ns: "{{ namespace }}"
            app_lkey: "{{ label.split('=')[0] }}"
            app_lvalue: "{{ label.split('=')[1] }}"
            delay: '2'
            retries: '60'
          
         ## POST-CHAOS APPLICATION LIVENESS CHECK

        - include_tasks: /common/utils/application_liveness_check.yml
          when: liveness_label != ''


        - set_fact:
            flag: "Pass"

      rescue: 
        - set_fact: 
            flag: "Fail"

      always: 

        ## RECORD END-OF-TEST IN LITMUS RESULT CR
 
        - include_tasks: /common/utils/update_litmus_result_resource.yml
          vars:
            status: 'EOT'
            chaostype: "{{ test_name }}"
