apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app-busybox
spec:
  template:
    metadata:
      labels:
        lkey: lvalue
    spec:
      containers:
      - name: app-busybox
        imagePullPolicy: IfNotPresent
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 10;done"]
        env:
        volumeMounts:
        - name: data-vol
          mountPath: /mnt/data
      volumes:
      - name: data-vol
        persistentVolumeClaim:
          claimName: testclaim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: testclaim
spec:
  storageClassName: testclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: teststorage
