---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: cstor-block-device-pool-provision-
  namespace: litmus
spec:
  template:
    metadata:
      name: litmus
      labels:
        app: cstor-block-device-pool-provision

    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: openebs/ansible-runner:ci
        imagePullPolicy: Always

        env:
          - name: ANSIBLE_STDOUT_CALLBACK
            #value: log_plays, actionable, default
            value: default

            # Provide name POOL_NAME for the cstor-pool
          - name: POOL_NAME
            value: cstor-block-disk-pool

           # Provide the value for POOL_TYPE 
           # Supported values: striped, mirrored, raidz ,raidz2
          - name: POOL_TYPE
            value: striped

          - name: OPERATOR_NS
            value: openebs

          - name: NODE_LABEL
            value: "node-role.kubernetes.io/compute=true"

          - name: DEVICE_CAPACITY
            value: "20Gi"

        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./providers/cstor/cstor-block-device-pool/test1.yml -i /etc/ansible/hosts -v; exit 0"]

