---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: litmus-cassandra-
  namespace: litmus
spec:
  template:
    metadata:
      name: litmus
      labels:
        app: cassandra-deployment-litmus

    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: openebs/ansible-runner:ci
        imagePullPolicy: Always

        env:
          - name: ANSIBLE_STDOUT_CALLBACK
            #value: log_plays
            value: default

          - name: PROVIDER_STORAGE_CLASS
            # Supported values: openebs-standard,openebs-standalone,local-storage
            value: openebs-standalone

            # Application pvc
          - name: APP_PVC
            value: openebs-cassandra

            # Application label
          - name: APP_LABEL
            value: 'app=cassandra'

            # Application namespace
          - name: APP_NAMESPACE
            value: app-cass-ns 

          - name: DEPLOY_TYPE
            value: statefulset

          - name: APP_REPLICA
            value: 'replicas=2'
            
          # Use 'deprovision' for app-clean up
          - name: ACTION
            value: provision

        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./cassandra/deployers/test.yml -i /etc/ansible/hosts -v; exit 0"]
