---
apiVersion: batch/v1
kind: Job
metadata:
  name: litmus-cassandra
  namespace: litmus 
spec:
  template:
    metadata:
      name: litmus
      labels:
        app: cassandra-deployment-litmus
   
    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: openebs/ansible-runner
        imagePullPolicy: Always

        env: 
          - name: ANSIBLE_STDOUT_CALLBACK
            #value: log_plays
            value: default

          - name: PROVIDER_STORAGE_CLASS
            # Supported values: openebs-standard, local-storage
            value: openebs-standard

            # Application pvc
          - name: APP_PVC
            value: openebs-cassandra
  
            # Application label
          - name: APP_LABEL
            value: 'app=cassandra'

            # Application namespace
          - name: APP_NAMESPACE
            value: litmus

          - name: DEPLOY_TYPE
            value: statefulset

        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./cassandra/deployers/test.yml -i /etc/ansible/hosts -v; exit 0"]
