---
- hosts: localhost
  connection: local

  vars_files:
    - test_vars.yml

  tasks:
    - block:

        ## Generating the testname for deployment
        - include_tasks: /common/utils/create_testname.yml

        ## RECORD START-OF-TEST IN LITMUS RESULT CR
        - include_tasks: /common/utils/update_litmus_result_resource.yml
          vars:
            status: 'SOT'

        ## Actual test
        ## Creating the namespaces and making application ready for deployment
        - include_tasks: /common/utils/pre_create_app_deploy.yml

        - name: Replace the default namespace in cassandra statefulset yaml
          replace:
            path: "{{ application_deployment }}"
            regexp: 'cassandra-0.cassandra.default.svc.cluster.local'
            replace: 'cassandra-0.cassandra.{{ app_ns }}.svc.cluster.local'

        ## Deploying the application
        - include_tasks: /common/utils/deploy_single_app.yml
          vars:
            check_app_pod: 'no'

        - name: Setting pass flag
          set_fact:
            flag: "Pass"

      rescue:
        - name: Setting fail flag
          set_fact:
            flag: "Fail"

      always:
            ## RECORD END-OF-TEST IN LITMUS RESULT CR
        - include_tasks: /common/utils/update_litmus_result_resource.yml
          vars:
            status: 'EOT'