apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber
  namespace: litmus
  labels:
    app: subscriber
spec:
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
    spec:
      containers:
        - name: igc
          image: 'litmuschaos/litmusportal-igc:ci'
          env:
            - name: GQL_SERVER
              value: #{SERVER}
            - name: CID
              value: #{CID}
            - name: KEY
              value: #{KEY}
        - name: agent
          image: 'litmuschaos/litmusportal-agent:ci'