apiVersion: v1
kind: Namespace
metadata:
  name: litmus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber
  namespace: litmus
  labels:
    app: subscriber
spec:
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
    spec:
      containers:
        - name: gql-node-master
          image: 'gdsoumya/gql-node-master'
          env:
            - name: GQL_SERVER
              value: #{SERVER}
            - name: CID
              value: #{CID}
            - name: KEY
              value: #{KEY}